server:
  port: 8080

management:
  health:
    redis:
      enabled: ${spinnaker.redis.enabled}

spinnaker:
  redis:
    enabled: false
    host: localhost
    port: 6379

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*

springdoc:
  writer-with-default-pretty-printer: true
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    url: /v3/api-docs.yaml
  api-docs:
    version: openapi_3_0
